[package]
name = "ayumu"
version = "0.3.6"
edition = "2021"
license = "MIT"
description = "A small, lightweight, user-oriented query language for search forms."

[dependencies]
nom = "7.1.3"
nom_locate = "4.2.0"
strsim = "0.11.1"
